# Generated by Django 3.0.5 on 2020-10-06 00:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('author', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='')),
                ('post', tinymce.models.HTMLField()),
            ],
        ),
    ]
