# Generated by Django 3.0.5 on 2020-10-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='Blog Post', max_length=140),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
