# Generated by Django 3.0.5 on 2020-08-29 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='number_of_teams',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='team',
            name='number_of_members',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
