# Generated by Django 3.0.5 on 2020-08-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoach', '0002_auto_20200829_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
    ]
