# Generated by Django 3.0.5 on 2020-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoach', '0005_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
