# Generated by Django 3.0.5 on 2020-09-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoach', '0007_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
