# Generated by Django 3.0.5 on 2020-09-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoach', '0010_auto_20200902_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
