# Generated by Django 3.0.5 on 2020-08-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coach_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
