# Generated by Django 3.0.5 on 2020-06-06 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200606_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionentry',
            name='date',
            field=models.DateField(default=datetime.date(2020, 6, 6)),
        ),
    ]
