# Generated by Django 3.0.5 on 2020-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200606_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionentry',
            name='date',
            field=models.DateField(),
        ),
    ]
