# Generated by Django 3.0.5 on 2020-06-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20200608_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('reflections', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='generaldayentry',
            name='reflections',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sessionentry',
            name='reflections',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sessionentry',
            name='target',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
