# Generated by Django 3.0.5 on 2020-06-11 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_result_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='position',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000)]),
        ),
    ]
