# Generated by Django 3.0.5 on 2020-07-13 15:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0009_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('Ultimate Goal', 'Ultimate Goal'), ('Long Term', 'Long Term'), ('Medium Term', 'Medium Term'), ('Short Term', 'Short Term')], max_length=40),
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_finished', models.CharField(choices=[('true', 'true'), ('false', 'false')], max_length=10)),
                ('objective_type', models.CharField(choices=[('Performance', 'Performance'), ('Intensity', 'Intensity'), ('Hours Worked', 'Hours Worked'), ('Finished', 'Finished')], max_length=20)),
                ('average', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('hours_of_work', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
