# Generated by Django 3.0.5 on 2020-07-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_auto_20200715_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='achieved',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=10),
        ),
    ]
