# Generated by Django 3.0.5 on 2020-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_goal_achieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('Ultimate', 'Ultimate'), ('Long Term', 'Long Term'), ('Medium Term', 'Medium Term'), ('Short Term', 'Short Term'), ('Finished', 'Finished')], max_length=40),
        ),
    ]
